"""empty message

Revision ID: 514fc8a41f4e
Revises: 
Create Date: 2022-10-14 07:22:26.267820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514fc8a41f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('commit', sa.String(length=255), nullable=True),
    sa.Column('back_info', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_contributes_id'), 'contributes', ['id'], unique=False)
    op.create_index(op.f('ix_contributes_time'), 'contributes', ['time'], unique=False)
    op.create_index(op.f('ix_contributes_type'), 'contributes', ['type'], unique=False)
    op.create_table('ontologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('intro', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('lastTime', sa.TIMESTAMP(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('is_editing', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontologies_id'), 'ontologies', ['id'], unique=False)
    op.create_table('ontologyTags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'ontology_id', 'tag_id')
    )
    op.create_table('recommends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.Column('ontology_name', sa.String(length=64), nullable=True),
    sa.Column('ontology_intro', sa.String(length=255), nullable=True),
    sa.Column('subscribe_nums', sa.Integer(), nullable=True),
    sa.Column('edit_nums', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('today_view_count', sa.Integer(), nullable=True),
    sa.Column('seven_days_view', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_recommends_edit_nums'), 'recommends', ['edit_nums'], unique=False)
    op.create_index(op.f('ix_recommends_id'), 'recommends', ['id'], unique=False)
    op.create_index(op.f('ix_recommends_subscribe_nums'), 'recommends', ['subscribe_nums'], unique=False)
    op.create_index(op.f('ix_recommends_today_view_count'), 'recommends', ['today_view_count'], unique=False)
    op.create_index(op.f('ix_recommends_view_count'), 'recommends', ['view_count'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('subscribes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('creat_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_subscribes_creat_time'), 'subscribes', ['creat_time'], unique=False)
    op.create_index(op.f('ix_subscribes_id'), 'subscribes', ['id'], unique=False)
    op.create_index(op.f('ix_subscribes_update_time'), 'subscribes', ['update_time'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('modifies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('handle_time_stamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('back_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifies_handle_time_stamp'), 'modifies', ['handle_time_stamp'], unique=False)
    op.create_index(op.f('ix_modifies_id'), 'modifies', ['id'], unique=False)
    op.create_index(op.f('ix_modifies_time_stamp'), 'modifies', ['time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modifies_time_stamp'), table_name='modifies')
    op.drop_index(op.f('ix_modifies_id'), table_name='modifies')
    op.drop_index(op.f('ix_modifies_handle_time_stamp'), table_name='modifies')
    op.drop_table('modifies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index(op.f('ix_subscribes_update_time'), table_name='subscribes')
    op.drop_index(op.f('ix_subscribes_id'), table_name='subscribes')
    op.drop_index(op.f('ix_subscribes_creat_time'), table_name='subscribes')
    op.drop_table('subscribes')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_recommends_view_count'), table_name='recommends')
    op.drop_index(op.f('ix_recommends_today_view_count'), table_name='recommends')
    op.drop_index(op.f('ix_recommends_subscribe_nums'), table_name='recommends')
    op.drop_index(op.f('ix_recommends_id'), table_name='recommends')
    op.drop_index(op.f('ix_recommends_edit_nums'), table_name='recommends')
    op.drop_table('recommends')
    op.drop_table('ontologyTags')
    op.drop_index(op.f('ix_ontologies_id'), table_name='ontologies')
    op.drop_table('ontologies')
    op.drop_index(op.f('ix_contributes_type'), table_name='contributes')
    op.drop_index(op.f('ix_contributes_time'), table_name='contributes')
    op.drop_index(op.f('ix_contributes_id'), table_name='contributes')
    op.drop_table('contributes')
    # ### end Alembic commands ###
